services:
  gitlab:
    image: gitlab/gitlab-ce:18.5.1-ce.0
    hostname: 'gitlab.local'
    # hostname: 'gitlab.securit.fr'
    ports:
      - "2222:22"
      - "80:80"
      - "443:443"
    volumes:
      - ${GITLAB_HOME}/data:/var/opt/gitlab
      - ${GITLAB_HOME}/logs:/var/log/gitlab
      - ${GITLAB_HOME}/config:/etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password
    networks:
      - gitlab-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      # test: ["CMD-SHELL", "curl -k https://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    deploy:
      mode: replicated
      replicas: 4
    networks:
      - gitlab-network

configs:
  gitlab:
    file: ./docker/gitlab/gitlab.rb

secrets:
  gitlab_root_password:
    external: true

networks:
  gitlab-network:
    driver: overlay